name: chat_app
description: A basic chat application using Firestore.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # database
  cloud_firestore: ^0.13.5

  # state management
  state_notifier: ^0.4.0
  flutter_state_notifier: ^0.4.2

  # di
  provider: ^4.1.0-dev+3

  # immutable class
  freezed_annotation:

  # json serialization
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generator
  build_runner:

  # immutable class
  freezed:

flutter:
  uses-material-design: true
  
  assets:
     - assets/images/


